apps/cliente/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from apps.cliente.views import ClienteCreate, ClienteList, ClienteDelete, ClienteUpdate
urlpatterns = [
    url(r'^create/$',login_required(ClienteCreate.as_view()), name='create_customer'),
    url(r'^read/$',login_required(ClienteList.as_view()), name='principal'),
    url(r'^update/(?P<pk>\w+)/$',login_required(ClienteUpdate.as_view()), name='update_customer'),
    url(r'^delete/(?P<pk>\w+)/$', login_required(ClienteDelete.as_view()), name='delete_customer'),
]

apps/mascota/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from apps.mascota.views import MascotaCreate, MascotaList, MascotaUpdate, MascotaDelete, mascota_list
urlpatterns = [
    url(r'^create/$',login_required(MascotaCreate.as_view()), name='create_pet'),
    url(r'^read/$',login_required(MascotaList.as_view()), name='principal'),
    url(r'^update/(?P<pk>\d+)/$',login_required(MascotaUpdate.as_view()), name='update_pet'),
    url(r'^delete/(?P<pk>\d+)/$', login_required(MascotaDelete.as_view()), name='delete_pet'),
    url(r'^read/(\w+)/$', mascota_list, name='reporte_mascota'),

]

veterinaria/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/', login, {'template_name':'login.html'}, name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^home/', include('apps.home.urls', namespace = "home")),
    url(r'^customer/', include('apps.cliente.urls', namespace = "customer")),
    url(r'^appointment/', include('apps.consulta.urls', namespace = "appointment")),
    url(r'^pet/', include('apps.mascota.urls', namespace="pet")),
    url(r'^doctor/', include('apps.medico.urls', namespace = "doctor")),
    url(r'^service/', include('apps.servicio.urls', namespace = "service")),
]

apps/cliente/models.py
from django.db import models
# Create your models here.
class Cliente(models.Model):
    rfc = models.CharField(max_length=16, primary_key=True)
    nombre = models.CharField(max_length=50)
    domicilio = models.CharField(max_length=50)
    telefono = models.CharField(max_length=12)
    email = models.EmailField()
    def __str__(self):
        return '{}'.format(self.rfc)

apps/cliente/forms.py
from django import forms
from apps.cliente.models import Cliente
class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente

        fields =[
        'rfc',
        'nombre',
        'domicilio',
        'telefono',
        'email',
        ]
        labels = {
        'rfc' : 'RFC',
        'nombre' : 'Nombre',
        'domicilio':'Domicilio',
        'telefono':'Telefono',
        'email':'Email',
        }
        widgets = {
        'rfc': forms.TextInput(),
        'nombre': forms.TextInput(),
        'domicilio': forms.TextInput(),
        'telefono': forms.TextInput(),
        'email': forms.EmailInput(),
        }
class ClienteUpdateForm(forms.ModelForm):
    class Meta:
        model = Cliente

        fields =[
        'nombre',
        'domicilio',
        'telefono',
        'email',
        ]
        labels = {
        'nombre' : 'Nombre',
        'domicilio':'Domicilio',
        'telefono':'Telefono',
        'email':'Email',
        }
        widgets = {
        'nombre': forms.TextInput(),
        'domicilio': forms.TextInput(),
        'telefono': forms.TextInput(),
        'email': forms.EmailInput(),
        }

apps/cliente/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from apps.cliente.models import Cliente
from apps.cliente.forms import ClienteForm, ClienteUpdateForm
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
# Create your views here.
class ClienteCreate(CreateView):
    model = Cliente
    form_class = ClienteForm
    template_name = 'cliente/altaCliente.html'
    success_url = reverse_lazy('pet:create_pet')

class ClienteList(ListView):
    model = Cliente
    template_name = 'cliente/reporteCliente.html'

class ClienteUpdate(UpdateView):
    model = Cliente
    form_class = ClienteUpdateForm
    template_name = 'cliente/actualizacionCliente.html'
    success_url = reverse_lazy('customer:principal')

class ClienteDelete(DeleteView):
    model = Cliente
    template_name = 'cliente/bajaCliente.html'
    success_url = reverse_lazy('customer:principal')

templates/cliente/actualizacionCliente.html
{% extends 'base/base1.html' %}
{% block title %}Cliente Alta{% endblock %}
{% block content %}
<p class="titulo">Actualizacion de datos del cliente</p>
<div class="col s12 m6 l4 offset-l4 formulario cyan teal lighten-5 z-depth-5">
<form method="post">
  {% csrf_token %}
  <div class="row col s12 m10 l8 offset-m1 offset-l2">
    <div class="input-field">
      {{form.nombre}}
      <label for="{{form.nombre.name}}">{{form.nombre.label}}</label>
    </div>
  </div>

  <div class="row col s12 m10 l8 offset-m1 offset-l2">
    <div class="input-field">
      {{form.domicilio}}
      <label for="{{form.domicilio.name}}">{{form.domicilio.label}}</label>
    </div>
  </div>

  <div class="row col s12 m10 l8 offset-m1 offset-l2">
    <div class="input-field">
      {{form.telefono}}
      <label for="{{form.telefono.name}}">{{form.telefono.label}}</label>
    </div>
  </div>

  <div class="row col s12 m10 l8 offset-m1 offset-l2">
    <div class="input-field">
      {{form.email}}
      <label for="{{form.email.name}}">{{form.email.label}}</label>
    </div>
  </div>
  <div class="row col s12 m12 l10 offset-m1 offset-l2">
    <button  class="btn waves-effect waves-light" type="submit">Guardar
      <i class="material-icons right" name="action">send</i>
    </button>
    <a class="btn btn-danger" href="{% url 'customer:principal' %}"> Cancelar</a>
  </div>
</form>
</div>
{% endblock %}

templates/cliente/altaCliente.html
{% extends 'base/base1.html' %}
{% block title %}Cliente Alta{% endblock %}
{% block content %}
<div class="col s12 m6 l4 offset-l4 formulario cyan teal lighten-5 z-depth-5">
  <p class="titulo">Alta cliente</p>
<form method="post">
  {% csrf_token %}
  <div class="row col s12 m10 l8 offset-m1 offset-l2">
    <div class="input-field">
      {{form.rfc}}
      <label for="{{form.rfc.name}}">{{form.rfc.label}}</label>
      <p>{{ form.rfc.errors }}</p>
    </div>
  </div>

  <div class="row col s12 m10 l8 offset-m1 offset-l2">
    <div class="input-field">
      {{form.nombre}}
      <label for="{{form.nombre.name}}">{{form.nombre.label}}</label>
    </div>
  </div>

  <div class="row col s12 m10 l8 offset-m1 offset-l2">
    <div class="input-field">
      {{form.domicilio}}
      <label for="{{form.domicilio.name}}">{{form.domicilio.label}}</label>
    </div>
  </div>

  <div class="row col s12 m10 l8 offset-m1 offset-l2">
    <div class="input-field">
      {{form.telefono}}
      <label for="{{form.telefono.name}}">{{form.telefono.label}}</label>
    </div>
  </div>

  <div class="row col s12 m10 l8 offset-m1 offset-l2">
    <div class="input-field">
      {{form.email}}
      <label for="{{form.email.name}}">{{form.email.label}}</label>
    </div>
  </div>
  <div class="row col s12 m12 l4 offset-m1 offset-l8">
    <button  class="btn waves-effect waves-light" type="submit">Guardar
      <i class="material-icons right" name="action">send</i>
    </button>
    <a class="btn btn-danger" href="{% url 'customer:principal' %}"> Cancelar</a>
  </div>
</form>
</div>
{% endblock %}

templates/cliente/bajaCliente.html
{% extends 'base/base1.html' %}

{% block content %}
<form method="post">
  {% csrf_token %}
  <h3>Se eleminara el registro de {{ object.nombre }}, desea continuar?</h3>
  <button class="btm btn-danger" type="submit">Si, eleminar</button>
  <a class="btn btn-default" href="{% url 'customer:principal' %}"> Cancelar</a>
</form>
{% endblock %}

templates/cliente/reporteCliente.html
{% extends 'base/base1.html' %}
{% block title %} Cliente {% endblock %}

{% block content %}
  <div class="row">
    <div class="col s12">
      <p class="titulo" style="margin-top: 0em; margin-bottom: 0em;">Clientes</p>
    </div>
    {% if object_list %}
  {% for cliente in object_list %}
  <div class="col s12 m6 l4">
    <div class="card teal lighten-5">
      <div class="card-content black-text">
        <span class="card-title">{{ cliente.nombre }}</span>
        <p>RFC: {{ cliente.rfc }}</p>
        <p>Domicilio: {{ cliente.domicilio }}</p>
        <p>Telefono: {{ cliente.telefono }}</p>
        <p>Email: {{ cliente.email }}</p>
        <a class="waves-effect waves-light btn" href="{% url 'pet:reporte_mascota' cliente.rfc %}">Mascotas</a>
      </div>
      <div class="row teal lighten-5">
        <div class="card-action col s10 m8 l6 offset-s2 offset-m3 offset-l4">
          <a class="btn-floating btn-large waves-effect waves-light red" href="{% url 'customer:update_customer' cliente.rfc %}"> <i class="material-icons">edit</i></a>
          <a class="btn-floating btn-large waves-effect waves-light darken-2" href="{% url 'customer:delete_customer' cliente.rfc %}"> <i class="material-icons">delete</i></a>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
  {% else %}
<h1>No hay registros</h1>
{% endif %}
  </div>
{% endblock %}