apps/cliente/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from apps.cliente.views import ClienteCreate, ClienteList, ClienteDelete, ClienteUpdate
urlpatterns = [
    url(r'^create/$',login_required(ClienteCreate.as_view()), name='create_customer'),
    url(r'^read/$',login_required(ClienteList.as_view()), name='principal'),
    url(r'^update/(?P<pk>\w+)/$',login_required(ClienteUpdate.as_view()), name='update_customer'),
    url(r'^delete/(?P<pk>\w+)/$', login_required(ClienteDelete.as_view()), name='delete_customer'),
]

apps/mascota/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from apps.mascota.views import MascotaCreate, MascotaList, MascotaUpdate, MascotaDelete, mascota_list
urlpatterns = [
    url(r'^create/$',login_required(MascotaCreate.as_view()), name='create_pet'),
    url(r'^read/$',login_required(MascotaList.as_view()), name='principal'),
    url(r'^update/(?P<pk>\d+)/$',login_required(MascotaUpdate.as_view()), name='update_pet'),
    url(r'^delete/(?P<pk>\d+)/$', login_required(MascotaDelete.as_view()), name='delete_pet'),
    url(r'^read/(\w+)/$', mascota_list, name='reporte_mascota'),

]

apps/medico/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from apps.medico.views import MedicoCreate, MedicoList, MedicoUpdate,MedicoDelete
urlpatterns = [
    url(r'^create/$',login_required(MedicoCreate.as_view()), name='create_doctor'),
    url(r'^read/$',login_required(MedicoList.as_view()), name='principal'),
    url(r'^update/(?P<pk>\w+)/$',login_required(MedicoUpdate.as_view()), name='update_doctor'),
    url(r'^delete/(?P<pk>\w+)/$', login_required(MedicoDelete.as_view()), name='delete_doctor'),
    ]

apps/servicio/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from apps.servicio.views import ServicioCreate, ServicioList, ServicioUpdate,ServicioDelete
urlpatterns = [
    url(r'^create/$',login_required(ServicioCreate.as_view()), name='create_service'),
    url(r'^read/$',login_required(ServicioList.as_view()), name='principal'),
    url(r'^update/(?P<pk>\w+)/$',login_required(ServicioUpdate.as_view()), name='update_service'),
    url(r'^delete/(?P<pk>\w+)/$', login_required(ServicioDelete.as_view()), name='delete_service'),
]

veterinaria/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/', login, {'template_name':'login.html'}, name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^home/', include('apps.home.urls', namespace = "home")),
    url(r'^customer/', include('apps.cliente.urls', namespace = "customer")),
    url(r'^appointment/', include('apps.consulta.urls', namespace = "appointment")),
    url(r'^pet/', include('apps.mascota.urls', namespace="pet")),
    url(r'^doctor/', include('apps.medico.urls', namespace = "doctor")),
    url(r'^service/', include('apps.servicio.urls', namespace = "service")),
]

templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <!--Import Google Icon Font-->
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>
    <link type="text/css" rel="stylesheet" href="{% static 'css/styles.css' %}"  media="screen,projection"/>
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <style>
    .demo-layout-transparent {
      background: url("{% static 'img/Mascota.png' %}");
    }
    </style>
  </head>
  <body>
    <div class="row">
      <div class="col s12 blue-grey linea"></div>
    </div>
    <div id="particles-js"></div>
    <div class="row cuerpo">
      <div class="col s12 m6 l4 offset-m2 offset-l4">{% block content %}{% endblock %}</div>
    </div>
    <!--Import jQuery before materialize.js-->
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>

    <footer class="us">
      <ul>
        <a>&copy; 2017  Innovasoft</a>
      </ul>
    </footer>
  </body>
</html>

templates/base/base1.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <!--Import Google Icon Font-->
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>
    <link type="text/css" rel="stylesheet" href="{% static 'css/styles.css' %}"  media="screen,projection"/>
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <style>
    .demo-layout-transparent {
      background: url("{% static 'img/Mascota.png' %}");
    }
    </style>
  </head>
  <body>
    <div class="row">
      <nav class="blue-grey">
        <!-- Dropdown Structure -->
        <ul id="cliente" class="dropdown-content">
          <li><a href="{% url 'customer:principal' %}">Reporte</a></li>
          <li class="divider"></li>
          <li><a href="{% url 'customer:create_customer' %}">Alta</a></li>
        </ul>
        <ul id="mascota" class="dropdown-content">
          <li><a href="{% url 'pet:principal' %}">Reporte</a></li>
          <li class="divider"></li>
          <li><a href="{% url 'pet:create_pet' %}">Alta</a></li>
        </ul>
        <ul id="medico" class="dropdown-content">
          <li><a href="{% url 'doctor:principal' %}">Reporte</a></li>
          <li class="divider"></li>
          <li><a href="{% url 'doctor:create_doctor' %}">Alta</a></li>
        </ul>
        <ul id="servicio" class="dropdown-content">
          <li><a href="{% url 'service:principal' %}">Reporte</a></li>
          <li class="divider"></li>
          <li><a href="{% url 'service:create_service' %}">Alta</a></li>
        </ul>

        <div class="nav-wrapper">
          <a href="#!" class="brand-logo">Pet la la land</a>
          <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
          <ul class="right hide-on-med-and-down">
            <li><a class="dropdown-button" href="#!" data-activates="cliente">Clientes</a></li>
            <li><a class="dropdown-button" href="#!" data-activates="mascota">Mascotas</a></li>
            <li><a class="dropdown-button" href="#!" data-activates="medico">Medicos</a></li>
            <li><a class="dropdown-button" href="#!" data-activates="servicio">Servicios</a></li>
            <li><a class="dropdown-button" href="{% url 'appointment:principal' %}">Consultas</a></li>
            <a class="btn-floating btn-large blue-grey" href="{% url 'logout'%}"> <i class="material-icons">power_settings_new</i></a>
          </ul>
          <ul class="side-nav blue-grey" id="mobile-demo">
            <ul class="collapsible" data-collapsible="accordion">
              <li>
                <div class="collapsible-header">Clientes</div>
                <div class="collapsible-body blue-grey lighten-2">
                  <a href="{% url 'customer:principal' %}">Reporte</a>
                  <a href="{% url 'customer:create_customer' %}">Alta</a>
                </div>
              </li>
              <li>
                <div class="collapsible-header">Mascotas</div>
                <div class="collapsible-body blue-grey lighten-2">
                  <a href="{% url 'pet:principal' %}">Reporte</a>
                  <a href="{% url 'pet:create_pet' %}">Alta</a>
                </div>
              </li>
              <li>
                <div class="collapsible-header">Medicos</div>
                <div class="collapsible-body blue-grey lighten-2">
                  <a href="{% url 'doctor:principal' %}">Reporte</a>
                  <a href="{% url 'doctor:create_doctor' %}">Alta</a>
                </div>
              </li>
              <li>
                <div class="collapsible-header">Servicios</div>
                <div class="collapsible-body blue-grey lighten-2">
                  <a href="{% url 'service:principal' %}">Reporte</a>
                  <a href="{% url 'service:create_service' %}">Alta</a>
                </div>
              </li>
              <a href="{% url 'appointment:principal' %}">Consultas</a>
              <a href="{% url 'logout'%}" class="waves-effect blue-grey lighten-2 btn">Cerrar sesion</a>
            </ul>
          </ul>
        </div>
      </nav>
    </div>
    <div class="row">
      {% block content %}{% endblock %}
    </div>
    <!--Import jQuery before materialize.js-->
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/javascript.js' %}"></script>
  </body>
  <footer class="usl us">
    <ul>
      <a>&copy; 2017  Innovasoft</a>
    </ul>
  </footer>
</html>