apps/servicio/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from apps.servicio.views import ServicioCreate, ServicioList, ServicioUpdate,ServicioDelete
urlpatterns = [
    url(r'^create/$',login_required(ServicioCreate.as_view()), name='create_service'),
    url(r'^read/$',login_required(ServicioList.as_view()), name='principal'),
    url(r'^update/(?P<pk>\w+)/$',login_required(ServicioUpdate.as_view()), name='update_service'),
    url(r'^delete/(?P<pk>\w+)/$', login_required(ServicioDelete.as_view()), name='delete_service'),
]

veterinaria/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/', login, {'template_name':'login.html'}, name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^home/', include('apps.home.urls', namespace = "home")),
    url(r'^customer/', include('apps.cliente.urls', namespace = "customer")),
    url(r'^appointment/', include('apps.consulta.urls', namespace = "appointment")),
    url(r'^pet/', include('apps.mascota.urls', namespace="pet")),
    url(r'^doctor/', include('apps.medico.urls', namespace = "doctor")),
    url(r'^service/', include('apps.servicio.urls', namespace = "service")),
]

apps/servicio/models.py
from django.db import models

# Create your models here.
class Servicio(models.Model):
    descripcion = models.CharField(max_length=50)
    precio = models.CharField(max_length=10)
    tipo = models.CharField(max_length=25)
    periodicidad = models.CharField(max_length=12)
    def __str__(self):
        return '{}'.format(self.descripcion)

apps/servicio/forms.py
from django import forms
from apps.servicio.models import Servicio
class ServicioForm(forms.ModelForm):
    class Meta:
        model = Servicio

        fields =[
        'descripcion',
        'precio',
        'tipo',
        'periodicidad',
        ]
        labels = {
        'descripcion':'Servicio',
        'precio':'Precio',
        'tipo':'Tipo',
        'periodicidad':'Periodicidad',
        }
        widgets = {
        'descripcion': forms.TextInput(),
        'precio': forms.NumberInput(),
        'tipo': forms.TextInput(),
        'periodicidad': forms.TextInput(),
        }

apps/servicio/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from apps.servicio.models import Servicio
from apps.servicio.forms import ServicioForm
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
# Create your views here.
class ServicioCreate(CreateView):
    model = Servicio
    form_class = ServicioForm
    template_name = 'servicio/altaServicio.html'
    success_url = reverse_lazy('service:principal')
class ServicioList(ListView):
    model = Servicio
    template_name = 'servicio/reporteServicio.html'

class ServicioUpdate(UpdateView):
    model = Servicio
    form_class = ServicioForm
    template_name = 'servicio/altaservicio.html'
    success_url = reverse_lazy('service:principal')

class ServicioDelete(DeleteView):
    model = Servicio
    template_name = 'servicio/bajaServicio.html'
    success_url = reverse_lazy('service:principal')

templates/servicio/altaServicio.html
{% extends 'base/base1.html' %}
{% block title %} Servicio Alta {% endblock %}
{% block content %}
<div class="formulario cyan teal lighten-5 z-depth-5 col s12 m6 l4 offset-l4">
<p class="titulo">Alta servicio</p>
<form method="post">
  {% csrf_token %}
  <div class="row col s12 m10 l8 offset-m1 offset-l2">
    <div class="input-field">
      {{form.descripcion}}
      <label for="{{form.descripcion.name}}">{{form.descripcion.label}}</label>
    </div>
  </div>

  <div class="row col s12 m10 l8 offset-m1 offset-l2">
    <div class="input-field">
      {{form.precio}}
      <label for="{{form.precio.name}}">{{form.precio.label}}</label>
      <p>{{ form.precio.errors }}</p>
    </div>
  </div>

  <div class="row col s12 m10 l8 offset-m1 offset-l2">
    <div class="input-field">
      {{form.tipo}}
      <label for="{{form.tipo.name}}">{{form.tipo.label}}</label>
    </div>
  </div>

  <div class="row col s12 m10 l8 offset-m1 offset-l2">
    <div class="input-field">
      {{form.periodicidad}}
      <label for="{{form.periodicidad.name}}">{{form.periodicidad.label}}</label>
    </div>
  </div>

  <div class="row col s12 m10 l8 offset-m1 offset-l2">
    <div class="input-field">
      {{form.email}}
      <label for="{{form.email.name}}">{{form.email.label}}</label>
    </div>
  </div>
  <div class="row col s12 m12 l10 offset-m1 offset-l2">
    <button  class="btn waves-effect waves-light" type="submit">Guardar
      <i class="material-icons right" name="action">send</i>
    </button>
    <a class="btn btn-danger" href="{% url 'service:principal' %}"> Cancelar</a>
  </div>
</form>
</div>
{% endblock %}

templates/servicio/bajaServicio.html
{% extends 'base/base1.html' %}

{% block content %}
<form method="post">
  {% csrf_token %}
  <h3>Se eleminara el registro de {{ object.descripcion }}, desea continuar?</h3>
  <button class="btm btn-danger" type="submit">Si, eleminar</button>
  <a class="btn btn-default" href="{% url 'service:principal' %}"> Cancelar</a>
</form>
{% endblock %}

templates/servicio/reporteServicio.html
{% extends 'base/base1.html' %}
{% block title %} Servicio{% endblock %}
{% block content %}
  <div class="row">
    <p class="titulo">Servicios</p>
    {% if object_list %}
  {% for servicio in object_list %}
  <div class="col s12 m6 l4">
    <div class="card teal lighten-5">
      <div class="card-content black-text">
        <span class="card-title">{{ servicio.descripcion }}</span>
        <p>Precio: {{ servicio.precio }}</p>
        <p>Tipo: {{ servicio.tipo }}</p>
        <p>Periodicidad: {{ servicio.periodicidad }}</p>
      </div>
      <div class="row teal lighten-5">
        <div class="card-action col s10 m8 l6 offset-s2 offset-m3 offset-l4">
          <a class="btn-floating btn-large waves-effect waves-light red" href="{% url 'service:update_service' servicio.id %}"> <i class="material-icons">edit</i></a>
          <a class="btn-floating btn-large waves-effect waves-light darken-2" href="{% url 'service:delete_service' servicio.id %}"> <i class="material-icons">delete</i></a>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
  {% else %}
<h1>No hay registros</h1>
{% endif %}
  </div>
{% endblock %}