apps/consulta/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from apps.consulta.views import ConsultaList, ConsultaCreate, ConsultaUpdate, ConsultaDelete, Consulta_list
urlpatterns = [
    url(r'^read/$',login_required(ConsultaList.as_view()), name='principal'),
    url(r'^read/(\d+)/$', Consulta_list, name='reporte_consulta'),
    url(r'^create/$',login_required(ConsultaCreate.as_view()), name='create_appointment'),
    url(r'^update/(?P<pk>\w+)/$',login_required(ConsultaUpdate.as_view()), name='update_appointment'),
    url(r'^delete/(?P<pk>\w+)/$', login_required(ConsultaDelete.as_view()), name='delete_appointment'),

]

apps/mascota/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from apps.mascota.views import MascotaCreate, MascotaList, MascotaUpdate, MascotaDelete, mascota_list
urlpatterns = [
    url(r'^create/$',login_required(MascotaCreate.as_view()), name='create_pet'),
    url(r'^read/$',login_required(MascotaList.as_view()), name='principal'),
    url(r'^update/(?P<pk>\d+)/$',login_required(MascotaUpdate.as_view()), name='update_pet'),
    url(r'^delete/(?P<pk>\d+)/$', login_required(MascotaDelete.as_view()), name='delete_pet'),
    url(r'^read/(\w+)/$', mascota_list, name='reporte_mascota'),

]

veterinaria/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/', login, {'template_name':'login.html'}, name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^home/', include('apps.home.urls', namespace = "home")),
    url(r'^customer/', include('apps.cliente.urls', namespace = "customer")),
    url(r'^appointment/', include('apps.consulta.urls', namespace = "appointment")),
    url(r'^pet/', include('apps.mascota.urls', namespace="pet")),
    url(r'^doctor/', include('apps.medico.urls', namespace = "doctor")),
    url(r'^service/', include('apps.servicio.urls', namespace = "service")),
]

apps/mascota/models.py
from django.db import models
from apps.cliente.models import Cliente
# Create your models here.

class Mascota(models.Model):
    nombre = models.CharField(max_length=25)
    especie = models.CharField(max_length=20)
    raza = models.CharField(max_length=20)
    color = models.CharField(max_length=20)
    tamano = models.CharField(max_length=20)
    senaParticular = models.CharField(max_length=20)
    fechaNacimiento = models.DateField()
    cliente = models.ForeignKey(Cliente, null = True, blank = True, on_delete = models.CASCADE,)
    def __str__(self):
        return '{}'.format(self.nombre)

apps/mascota/forms.py
from django import forms
from apps.mascota.models import Mascota
class MascotaForm(forms.ModelForm):
    class Meta:
        model = Mascota

        fields =[
        'nombre',
        'especie',
        'raza',
        'color',
        'tamano',
        'senaParticular',
        'fechaNacimiento',
        'cliente',
        ]
        labels = {
        'nombre':'Nombre',
        'especie':'Especie',
        'raza':'Raza',
        'color':'Color',
        'tamano':'Tamaño',
        'senaParticular':'Seña Particular',
        'fechaNacimiento' :'Fecha de Nacimiento',
        'cliente':'Cliente',
        }
        widgets = {
        'nombre':forms.TextInput(),
        'especie':forms.TextInput(),
        'raza':forms.TextInput(),
        'color':forms.TextInput(),
        'tamano':forms.TextInput(),
        'senaParticular':forms.TextInput(),
        'fechaNacimiento':forms.DateInput(),
        'cliente':forms.TextInput(),
        }

apps/mascota/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from apps.mascota.models import Mascota
from apps.mascota.forms import MascotaForm
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
# Create your views here.
class MascotaCreate(CreateView):
    model = Mascota
    form_class = MascotaForm
    template_name = 'mascota/altaMascota.html'
    success_url = reverse_lazy('pet:principal')

class MascotaList(ListView):
    model = Mascota
    template_name = 'mascota/reporteMascota.html'

def mascota_list(request,rfc_cliente):
    mascota = Mascota.objects.filter(cliente = rfc_cliente)
    contexto = {'mascotas':mascota}
    return render(request, 'mascota/reportesMascota.html', contexto)

class MascotaUpdate(UpdateView):
    model = Mascota
    form_class = MascotaForm
    template_name = 'mascota/altaMascota.html'
    success_url = reverse_lazy('pet:principal')

class MascotaDelete(DeleteView):
    model = Mascota
    template_name = 'mascota/bajaMascota.html'
    success_url = reverse_lazy('pet:principal')

templates/mascota/altaMascota.html
{% extends 'base/base1.html' %}
{% block content %}
<div class="col s12 m6 l4 offset-l4">
  <p class="titulo">Alta mascota</p>
<form method="post">
  {% csrf_token %}
  <div class="row col s12 m10 l8 offset-m1 offset-l2">
    <div class="input-field">
      {{form.nombre}}
      <label for="{{form.nombre.name}}">{{form.nombre.label}}</label>
    </div>
  </div>

  <div class="row col s12 m10 l8 offset-m1 offset-l2">
    <div class="input-field">
      {{form.especie}}
      <label for="{{form.especie.name}}">{{form.especie.label}}</label>
    </div>
  </div>

  <div class="row col s12 m10 l8 offset-m1 offset-l2">
    <div class="input-field">
      {{form.raza}}
      <label for="{{form.raza.name}}">{{form.raza.label}}</label>
    </div>
  </div>

  <div class="row col s12 m10 l8 offset-m1 offset-l2">
    <div class="input-field">
      {{form.color}}
      <label for="{{form.color.name}}">{{form.color.label}}</label>
    </div>
  </div>
  <div class="row col s12 m10 l8 offset-m1 offset-l2">
    <div class="input-field">
      {{form.tamano}}
      <label for="{{form.tamano.name}}">{{form.tamano.label}}</label>
    </div>
  </div>

  <div class="row col s12 m10 l8 offset-m1 offset-l2">
    <div class="input-field">
      {{form.senaParticular}}
      <label for="{{form.senaParticular.name}}">{{form.senaParticular.label}}</label>
    </div>
  </div>
  <div class="row col s12 m10 l8 offset-m1 offset-l2">
    <div class="input-field">
      {{form.fechaNacimiento}}
      <label for="{{form.fechaNacimiento.name}}">{{form.fechaNacimiento.label}}</label>
      <p>{{ form.fechaNacimiento.errors }}</p>
    </div>
  </div>
  <div class="row col s12 m10 l8 offset-m1 offset-l2">
    <div class="input-field">
      {{form.cliente}}
      <label for="{{form.cliente.name}}">{{form.cliente.label}}</label>
      <p>{{ form.cliente.errors }}</p>
    </div>
  </div>
  <div class="row col s12 m12 l10 offset-m1 offset-l2">
    <button  class="btn waves-effect waves-light" type="submit">Guardar
      <i class="material-icons right" name="action">send</i>
    </button>
    <a class="btn btn-danger" href="{% url 'pet:principal' %}"> Cancelar</a>
  </div>
</form>
</div>
{% endblock %}

templates/mascota/bajaMascota.html
{% extends 'base/base1.html' %}

{% block content %}
<form method="post">
  {% csrf_token %}
  <h3>Se eleminara el registro de {{ object.nombre }}, desea continuar?</h3>
  <button class="btm btn-danger" type="submit">Si, eleminar</button>
  <a class="btn btn-default" href="{% url 'pet:principal' %}"> Cancelar</a>
</form>
{% endblock %}

templates/mascota/reporteMascota.html
{% extends 'base/base1.html' %}
{% block title %} Mascota {% endblock %}

{% block content %}
  <div class="row">
    <p class="titulo">Mascotas</p>
    {% if object_list %}
      {% for mascota in object_list %}
      <div class="col s12 m6 l4">
        <div class="card teal lighten-5">
          <div class="card-content black-text">
            <span class="card-title">{{ mascota.nombre }}</span>
            <p>Especie: {{ mascota.especie }}</p>
            <p>Raza: {{ mascota.raza }}</p>
            <p>Color: {{ mascota.color }}</p>
            <p>Seña Particular: {{ mascota.senaParticular }}</p>
            <p>Fecha de Nacimiento: {{ mascota.fechaNacimiento }}</p>
            <p>Dueño: {{ mascota.cliente.nombre }}</p>
            <a class="waves-effect waves-light btn" href="{% url 'appointment:reporte_consulta' mascota.id %}">Consultas</a>
          </div>
          <div class="row teal lighten-5">
            <div class="card-action col s10 m8 l6 offset-s2 offset-m3 offset-l4">
              <a class="btn-floating btn-large waves-effect waves-light red" href="{% url 'pet:update_pet' mascota.id %}"> <i class="material-icons">edit</i></a>
              <a class="btn-floating btn-large waves-effect waves-light darken-2" href="{% url 'pet:delete_pet' mascota.id %}"> <i class="material-icons">delete</i></a>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    {% else %}
  <h1>No hay registros</h1>
    {% endif %}
  </div>
{% endblock %}

templates/mascota/reportesMascota.html
{% extends 'base/base1.html' %}
{% block title %} Mascota {% endblock %}

{% block content %}
  <div class="row">
    {% if mascotas %}
      <p class="titulo">Mascotas de {{ mascota.cliente.nombre }}</p>
      {% for mascota in mascotas %}
      <div class="col s12 m6 l4">
        <div class="card teal lighten-5">
          <div class="card-content black-text">
            <span class="card-title">{{ mascota.nombre }}</span>
            <p>Especie: {{ mascota.especie }}</p>
            <p>Raza: {{ mascota.raza }}</p>
            <p>Color: {{ mascota.color }}</p>
            <p>Seña Particular: {{ mascota.senaParticular }}</p>
            <p>Fecha de Nacimiento: {{ mascota.fechaNacimiento }}</p>
            <p>Dueño: {{ mascota.cliente.nombre }}</p>
          </div>
          <div class="row teal lighten-5">
            <div class="card-action col s10 m8 l6 offset-s2 offset-m3 offset-l4">
              <a class="btn-floating btn-large waves-effect waves-light red" href="{% url 'pet:update_pet' mascota.id %}"> <i class="material-icons">edit</i></a>
              <a class="btn-floating btn-large waves-effect waves-light darken-2" href="{% url 'pet:delete_pet' mascota.id %}"> <i class="material-icons">delete</i></a>
            </div>
          </div>
        </div>
      </div>
        {% endfor %}
    {% else %}
  <h1>No hay registros</h1>
    {% endif %}
  </div>
{% endblock %}